routes/web.php
<?php

use App\Http\Controllers\BlogpostController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\UserController;
use App\Mail\BlogpostDigest;
use App\Models\Blogpost;
use App\Models\User;
use Illuminate\Support\Facades\{Auth,Route};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// blogposts
Route::get('blogposts', [BlogpostController::class, 'index'])->name('blogposts.index');

Route::get('blogposts/create', [BlogpostController::class, 'create'])->name('blogposts.create');
Route::post('blogposts', [BlogpostController::class, 'store'])->name('blogposts.store');

Route::get('blogposts/{blogpost}', [BlogpostController::class, 'show'])->name('blogposts.show');
Route::get('blogposts/{blogpost}/edit', [BlogpostController::class, 'edit'])->name('blogposts.edit');
Route::put('blogposts/{blogpost}', [BlogpostController::class, 'update'])->name('blogposts.update');
Route::delete('blogposts/{blogpost}', [BlogpostController::class, 'destroy'])->name('blogposts.delete');

// categories
Route::get('categories/{category}', [CategoryController::class, 'show'])->name('categories.show');

// ajax categories
Route::any('ajax/categories', [CategoryController::class, 'ajax'])->name('categories.ajax');

// comments
Route::post('comments/{blogpost}', [CommentController::class, 'store'])->name('comments.store');
Route::put('comments/{comment}', [CommentController::class, 'update'])->name('comments.update');
Route::delete('comments/{comment}', [CommentController::class, 'destroy'])->name('comments.delete');

// users
Route::get('users', [UserController::class, 'index'])->name('users.index');
Route::get('users/{user}', [UserController::class, 'show'])->name('users.show');

// subscriptions
Route::get('subscriptions', [SubscriptionController::class, 'index'])->name('subscriptions.index')->middleware('auth');
Route::get('subscriptions/{author}', [SubscriptionController::class, 'create'])->name('subscriptions.create');
Route::post('subscriptions/{author}', [SubscriptionController::class, 'store'])->name('subscriptions.store');
Route::delete('subscriptions/{author}', [SubscriptionController::class, 'destroy'])->name('subscriptions.delete');

// mailable preview
Route::get('mailable', function() {
    $user = User::where('email', 'guest@example.com')->first();
    $blogposts = Blogpost::orderBy('created_at', 'desc')->take(3)->get();

    return new BlogpostDigest($user, $blogposts);
});

// site index
Route::redirect('/', 'blogposts');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Models/Blogpost.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;


class Blogpost extends Model
{
    use HasFactory, Sluggable;

    protected $fillable = [
        'title',
        'image',
        'body',
        'subscription_only',
    ];

    public function comments()
    {
        return $this->hasMany(Comment::class)->orderBy('created_at', 'desc'); // newest first?
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class)->withTimestamps()->orderBy('title');
    }

    public function getPath()
    {
        return route('blogposts.show', $this);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function getImageAsset()
    {
        if (filter_var($this->image, FILTER_VALIDATE_URL)) {
            return asset($this->image);
        }

        return asset(implode('/', ['storage', $this->image]));
    }
}

app/Http/Controllers/BlogpostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreBlogpost;
use App\Models\Blogpost;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BlogpostController extends Controller
{

    public function __construct()
    {
        $this->authorizeResource(Blogpost::class, 'blogpost');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $blogposts = Blogpost::withCount(['comments'])
            ->orderBy('created_at', 'desc')
            ->paginate(10);
        return view('blogposts.index', compact([
            'blogposts'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $blogpost = new Blogpost();
        $categories = Category::all();
        return view('blogposts.create', compact(['blogpost', 'categories']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBlogpost $request)
    {
        $formData = $this->handleImageUpload($request, null);

        $blogpost = Blogpost::make($formData);
        $blogpost->user()->associate(Auth::user());
        $blogpost->save();

        if ($request->has('categories')) {
            $blogpost->categories()->attach($formData['categories']);
        }

        // redirect to the new blogpost
        return redirect(route('blogposts.show', $blogpost));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Blogpost  $blogpost
     * @return \Illuminate\Http\Response
     */
    public function show(Blogpost $blogpost)
    {
        // $blogpost->loadCount(['categories', 'comments',]);
        return view('blogposts.show', compact([
            'blogpost'
        ]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Blogpost  $blogpost
     * @return \Illuminate\Http\Response
     */
    public function edit(Blogpost $blogpost)
    {
        $categories = Category::all();
        return view('blogposts.edit', compact(['blogpost', 'categories']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Blogpost  $blogpost
     * @return \Illuminate\Http\Response
     */
    public function update(StoreBlogpost $request, Blogpost $blogpost)
    {
        $formData = $this->handleImageUpload($request, $blogpost);

        $blogpost->update($formData); // fill + save

        if ($request->has('categories')) {
            $blogpost->categories()->sync($formData['categories']); // update categories
        } else {
            $blogpost->categories()->detach();
        }

        // redirect to the new blogpost
        return redirect(route('blogposts.show', $blogpost));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Blogpost  $blogpost
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blogpost $blogpost)
    {
        $blogpost->delete();
        return redirect(route('users.show', Auth::user()));
    }

    protected function handleImageUpload(Request $request, ?Blogpost $blogpost)
    {
        $formData = $request->validated();

        // store the image
        if ($request->has('image')) {
            $formData['image'] = $request->file('image')->store('blogposts', 'public');
        } else {
            $formData['image'] = optional($blogpost)->image;
        }

        return $formData;
    }
}

resources/views/blogposts/partials/form-fields.blade.php
@csrf

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="form-group">
    <label for="title" @error('title') class="text-danger" @enderror>Title</label>
    <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title"
        value="{{ old('title', optional($blogpost)->title) }}" maxlength="255">
    @error('title')
    <div class="invalid-feedback">{{ $errors->first('title') }}</div>
    @enderror
</div>
<div class="form-group">
    <label for="image" @error('image') class="text-danger" @enderror>Image</label>
    @if (optional($blogpost)->image)
        <div class="mb-3"><img src="{{ $blogpost->getImageAsset() }}" alt="" class="w-50"></div>
    @endif
    <input type="file" class="form-control-file @error('image') is-invalid @enderror" id="image" name="image">
    @error('image')
    <div class="invalid-feedback">{{ $errors->first('image') }}</div>
    @enderror
</div>
<div class="form-group">
    <label for="body" @error('body') class="text-danger" @enderror>Blog</label>
    <textarea class="form-control @error('body') is-invalid @enderror" name="body" id="body"
        rows="10">{{ old('body', optional($blogpost)->body) }}</textarea>
    @error('body')
    <div class="invalid-feedback">{{ $errors->first('body') }}</div>
    @enderror
</div>
<div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="subscription_only" name="subscription_only" @if (old('subscription_only', optional($blogpost)->subscription_only))
    checked @endif>
    <label for="subscription_only" class="form-check-label">Subscription only</label>
</div>
<div class="form-group">
    <label @error('categories') class="text-danger" @enderror>Categories</label>
    <div>
        @forelse ($categories as $i => $category)
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="categories[]" id="category{{ $i }}"
                    value="{{ $category->id }}" @if ($blogpost->categories->contains($category)) checked @endif>
                <label class="form-check-label" for="category{{ $i }}">{{ $category->title }}</label>
            </div>
        @empty
            <span class="text-warning">There are no categories available yet.</span>
        @endforelse
    </div>
    @error('categories')
    <div class="invalid-feedback">{{ $errors->first('categories') }}</div>
    @enderror
</div>

resources/views/blogposts/partials/list.blade.php
<div class="row pt-md-4">
    <div id="blogpost" class="col-md-12">
        @foreach ($blogposts as $blogpost)
            <div class="blog-entry d-md-flex ftco-animate">
                <a href="{{ $blogpost->getPath() }}" class="img img-2"
                    style="background-image: url({{ $blogpost->getImageAsset() }});"></a>
                <div class="text text-2 pl-md-4">
                    <h3 class="mb-2">
                        @if ($blogpost->subscription_only)
                            <i class="icon-paypal mr-2 @if($blogpost->user->subscribers->contains(Auth::user()))
                                text-success
                            @else
                                text-danger
                            @endif "></i>
                        @endif
                        <a href="{{ $blogpost->getPath() }}">{{ $blogpost->title }}</a>
                    </h3>

                    @include('blogposts.partials.writer-buttons')

                    <div class="meta-wrap">
                        <p class="meta">
                            <span><i class="icon-calendar mr-2"></i>{{ $blogpost->created_at }}</span>
                            <span>
                                @foreach ($blogpost->categories as $category)
                                    <a href="{{ $category->getPath() }}"><i
                                            class="icon-folder-o mr-2"></i>{{ $category->title }}</a>
                                @endforeach
                            </span>
                            <span><i class="icon-comment2 mr-2"></i>{{ $blogpost->comments_count }}
                                Comment{{ $blogpost->comments_count === 1 ? '' : 's' }}</span>
                        </p>
                    </div>
                    <p class="mb-4">{{ $blogpost->content }}</p>
                    <p>
                        @can('view', $blogpost)
                            <a href="{{ $blogpost->getPath() }}" class="btn-custom">Read More <span
                                    class="ion-ios-arrow-forward"></span></a>
                        @else
                            <a href="{{ route('subscriptions.create', $blogpost->user) }}"><i class="icon-cc-paypal"></i>
                                Subscribe for premium content <span class="ion-ios-arrow-forward"></span></a>
                        @endcan

                    </p>
                </div>
            </div>
        @endforeach
    </div>
</div><!-- END-->

resources/views/blogposts/partials/writer-buttons.blade.php
@can(['update', 'delete'], $blogpost)
    <div class="mb-3">
        <a class="btn btn-sm btn-warning" href="{{ route('blogposts.edit', $blogpost) }}">Edit</a>
        <form class="d-inline" action="{{ route('blogposts.delete', $blogpost) }}" method="post">
            @csrf
            @method('delete')
            <button class="btn btn-sm btn-danger">Delete</button>
        </form>
    </div>
@endcan